### ISSUE TITLE
Update to Spring Boot version 3

### ISSUE THREAD

**Issue by marshallmcdonnell** [smart-spectral-matching/ssm-ui-ml#3]
Would like to move to new versions of spring boot for maintenance.
Currently, at 3.0.6 (the [catalog service](https://github.com/smart-spectral-matching/ssm-service-catalog) is switching to this version)

This isn't a trivial jump since it requires...

- Updating to at least Java version 17
- The update on Java also required me to update maven locally (had to install from release; version in `apt` for Ubuntu 20.04 was too old)
- Would need to update dockerfiles
- Would need to update other dependencies in the pom.xml related to this change.
- Not totally sure but this would probably affect Vaadin version as well?

**Comment by vishalsingh2972** [comment]
Hey @marshallmcdonnell could you please review PR https://github.com/smart-spectral-matching/ssm-ui-ml/pull/4

**Comment by marshallmcdonnell** [comment]
@vishalsingh2972 Thank you! Will do. I added @SmithRWORNL on the review as well since he is the lead dev on this service.

**Comment by vishalsingh2972** [comment]
issue solved and merged PR #4

**Comment by marshallmcdonnell** [comment]
Closing, thanks again @vishalsingh2972
